// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfknanpcljofrkmphffm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhma25hbnBjbGpvZnJrbXBoZmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3MTM0OTgsImV4cCI6MjA1MTI4OTQ5OH0.AaMCGZlVbBq4eAzOoyTj6wih_bayGvcntl8naMNjlrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);